SPANISH_SUPPLIER_NAME = "José Álvarez S.L."
SPANISH_CITY = "Málaga"
SPANISH_ADDRESS_LABEL = "Dirección"
SPANISH_NUMBER_LABEL = "Número"
SPANISH_COUNTRY = "España"

UNICODE_FIXTURES = [
    SPANISH_SUPPLIER_NAME,
    SPANISH_CITY,
    SPANISH_ADDRESS_LABEL,
    SPANISH_NUMBER_LABEL,
    SPANISH_COUNTRY,
]
